version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: feature/v4
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.29
    - 14.14.32
    - 15.0.0
  - dependency-name: react-virtuoso
    versions:
    - 1.8.2
    - 1.8.3
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.2.3
  - dependency-name: webpack
    versions:
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.27.1
    - 5.31.1
    - 5.34.0
  - dependency-name: ts-loader
    versions:
    - 8.0.16
    - 9.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 12.7.2
    - 12.7.3
    - 12.7.4
    - 12.8.0
    - 13.0.11
    - 13.0.12
    - 13.0.14
    - 13.0.15
    - 13.0.5
    - 13.1.0
  - dependency-name: node-kakao
    versions:
    - 3.1.9
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.0.4
    - 4.0.5
    - 4.0.6
    - 4.1.0
  - dependency-name: wait-on
    versions:
    - 5.2.2
  - dependency-name: image-size
    versions:
    - 0.9.6
  - dependency-name: open-graph-scraper
    versions:
    - 4.8.1
  - dependency-name: bson
    versions:
    - 4.2.3
  - dependency-name: html-webpack-plugin
    versions:
    - 5.3.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
    - 4.2.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
