[package]
name = "talk-loco-client"
keywords = ["talk", "loco"]
readme = "README.md"
description = "Loco client"
version = "0.5.1"

license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[features]
wasm = ["futures-loco-protocol/wasm"]

[dependencies]
parking_lot = "0.12.1"
serde = { version = "1.0" }
serde_with = "3.4.0"
bson = "2.7.0"
futures-loco-protocol = "0.4.0"
thiserror = "1.0"
async-stream = "0.3.5"
pin-project-lite = "0.2.13"
futures-lite = "2.0.1"
structstruck = "0.4.1"
bitflags = { version = "2.4.1", features = ["serde"] }
num-bigint-dig = "0.8.4"
serde-byte-array = "0.1.2"

[dev-dependencies]
tokio-native-tls = "0.3.1"
tokio-util = { version = "0.7.10", features = ["compat"] }
tokio = { version = "1", features = ["full"] }
