name: auto-merge

on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: major
        command: squash and merge
        github-token: "${{ secrets.GITHUB_TOKEN }}"
